Improved Oracle Support
kristijanhusak/vim-dadbod-completion pull request #13
Opened 2020-11-09 21:04 UTC by Iron-E

I'm opening this pull to go along with kristijanhusak/vim-dadbod-ui#68. This PR ~~will~~ add first-class support for Oracle databases to this plugin ~~when it is done~~. 

So far, I can make this implementation work inconsistently. There something wrong and I don't know what yet; it's either the amount of time required to do the queries and cache the completion, or some sequence of events which make it work. I'm going to keep digging while the other PR is looked over.

![Completion](https://user-images.githubusercontent.com/36409591/98596171-0f811c80-22a5-11eb-9d1b-fd68c7c4334a.png)

2020-11-09 21:24 UTC, Iron-E commented
Here it is failing:

![Error](https://user-images.githubusercontent.com/36409591/98597971-c7afc480-22a7-11eb-955a-031985822f0c.png)

It seems like switching buffers is a part of it. I'll keep looking.

2020-11-10 01:21 UTC, Iron-E commented
Got it working. Oracle keeps a _lot_ of information about the database in the system catalog, so I sped up the result caching by adding a restriction to the queries which only reports tables created by users.

I figure that if a table is owned by the system, then LSP completion for a specific database scheme should kick in.

2020-11-10 01:22 UTC, Iron-E commented on autoload/vim_dadbod_completion.vim
> -  if a:0 > 0
This condition caused errors to be flashed at the user whenever certain `#job#run()`s had not finished. The revised condition allows the operation to silently fail while waiting for the jobs to finish.

2020-11-10 01:23 UTC, Iron-E commented on autoload/vim_dadbod_completion.vim
> +  return db#url#parse(a:db).scheme ==? 'oracle' ? printf('%s %s', Query, base_query) : printf('%s %s', base_query, Query)
`sqlplus` piping logic ported to this repository.

2020-11-10 01:24 UTC, Iron-E commented on autoload/vim_dadbod_completion/schemas.vim
> +let s:oracle_args = "echo \"SET linesize 4000;\nSET pagesize 4000;\n%s\" | "
I had to create separate variables, since Oracle's system catalog structure is quite different from MySQL and Postgres.

2020-11-10 04:37 UTC, Iron-E commented on autoload/vim_dadbod_completion.vim
>    endif
`Query` is used as a function, but `Query` isn't ready until another `#job#run()` has complete. `Query` would sometimes be a string and this condition would also pass, so I adjusted the condition to match what the enclosing statements require.

2020-11-15 10:32 UTC, kristijanhusak requested changes

2020-11-15 18:39 UTC, Iron-E commented on autoload/vim_dadbod_completion/schemas.vim
> +\   'table_column_query': printf(s:oracle_args, printf(s:oracle_base_column_query, "AND C.table_name='{db_tbl_name}'")),
I can't believe I didn't see that! Makes me impressed that the plugin was able to even provide table-specific completion while I had it wrong

2020-11-15 18:43 UTC, kristijanhusak commented on autoload/vim_dadbod_completion/schemas.vim
> +\   'table_column_query': printf(s:oracle_args, printf(s:oracle_base_column_query, "AND C.table_name='{db_tbl_name}'")),
It probably just gave you all columns completion, instead of scoping it to the table. Should be good now, thanks.

2020-11-15 18:43 UTC, kristijanhusak commented
Looks good now, thanks!

2020-11-15 18:43 UTC, merged